### Task1:

In [2]:
import numpy as np

In [4]:
HR=np.arange(1,4)
IT=np.arange(4,19)
Finance=np.arange(19,24)
Sales=np.arange(24,31)

In [5]:
print(HR)
print(IT)
print(Finance)
print(Sales)

[1 2 3]
[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[19 20 21 22 23]
[24 25 26 27 28 29 30]


### Task2:

In [10]:
s_hr=np.array([50000,60000,57000])
s_it=np.full(15,67000)
s_finance=np.array([60000,65000,50000,70000,87000])
s_sales=np.array([50000,60000,65000,90000,56000,65000,71000])

In [11]:
print(s_hr)
print(s_it)
print(s_finance)
print(s_sales)

[50000 60000 57000]
[67000 67000 67000 67000 67000 67000 67000 67000 67000 67000 67000 67000
 67000 67000 67000]
[60000 65000 50000 70000 87000]
[50000 60000 65000 90000 56000 65000 71000]


### Task3:

In [12]:
avg_hr=np.mean(s_hr)
avg_it=np.mean(s_it)
avg_finance=np.mean(s_finance)
avg_sales=np.mean(s_sales)

In [13]:
print(avg_hr)
print(avg_it)  #IT Department has highest average salary expense on the employees
print(avg_finance) 
print(avg_sales)

55666.666666666664
67000.0
66400.0
65285.71428571428


### Task4:

In [16]:
np.max(s_hr) #Highest salary of HR department

60000

In [17]:
np.max(s_finance) #Highest salary of Finance department

87000

### Task5:

In [21]:
new_sal_IT=s_it*1.05 
print(new_sal_IT)

[70350. 70350. 70350. 70350. 70350. 70350. 70350. 70350. 70350. 70350.
 70350. 70350. 70350. 70350. 70350.]
