In [1]:
import numpy as np

In [3]:
data=np.genfromtxt('DS1_C4_S1_Shopping_Data_Challenge.csv',delimiter=',',skip_header=1)

### Task1:

In [25]:
index=np.where(data[:,3]>80)
details=data[index]
count=np.array(index)
print("The count of xustomer whose spending score is above 80 is: ",count.size)
print()
print(details)


The count of xustomer whose spending score is above 80 is:  30

[[  2.  21.  15.  81.]
 [  8.  23.  18.  94.]
 [ 12.  35.  19.  99.]
 [ 20.  35.  23.  98.]
 [ 26.  29.  28.  82.]
 [ 30.  23.  29.  87.]
 [ 34.  18.  33.  92.]
 [ 36.  21.  33.  81.]
 [ 42.  24.  38.  92.]
 [124.  39.  69.  91.]
 [128.  40.  71.  95.]
 [136.  29.  73.  88.]
 [142.  32.  75.  93.]
 [144.  32.  76.  87.]
 [146.  28.  77.  97.]
 [150.  34.  78.  90.]
 [152.  39.  78.  88.]
 [156.  27.  78.  89.]
 [162.  29.  79.  83.]
 [164.  31.  81.  93.]
 [168.  33.  86.  95.]
 [174.  36.  87.  92.]
 [176.  30.  88.  86.]
 [180.  35.  93.  90.]
 [182.  32.  97.  86.]
 [184.  29.  98.  88.]
 [186.  30.  99.  97.]
 [190.  36. 103.  85.]
 [194.  38. 113.  91.]
 [200.  30. 137.  83.]]


### Task2:

In [32]:
index=np.where((data[:,1]>=20)&(data[:,1]<=24))
a=data[index]
print(a)

[[  2.  21.  15.  81.]
 [  3.  20.  16.   6.]
 [  4.  23.  16.  77.]
 [  6.  22.  17.  76.]
 [  8.  23.  18.  94.]
 [ 14.  24.  20.  77.]
 [ 16.  22.  20.  79.]
 [ 18.  20.  21.  66.]
 [ 30.  23.  29.  87.]
 [ 32.  21.  30.  73.]
 [ 36.  21.  33.  81.]
 [ 40.  20.  37.  75.]
 [ 42.  24.  38.  92.]
 [ 46.  24.  39.  65.]
 [ 79.  23.  54.  52.]
 [ 85.  21.  54.  57.]
 [ 88.  22.  57.  55.]
 [ 96.  24.  60.  52.]
 [100.  20.  61.  49.]
 [101.  23.  62.  41.]
 [106.  21.  62.  42.]
 [125.  23.  70.  29.]
 [135.  20.  73.   5.]]


### Task3:

In [51]:
max_sal=np.max(data[:,2])
min_sal=np.min(data[:,2])
index=np.where((data[:,2]==max_sal) | (data[:,2]==min_sal))
ID=data[:,0][index]
print(ID)

[  1.   2. 199. 200.]


### Task4:

In [57]:
index=np.where((data[:,1]<45)&(data[:,2]>35)&(data[:,3]>75))
details=data[index]
count=np.array(index)
print("Number of customers that satisfy above conditions are: ",count.size)
print()
print(details)

Number of customers that satisfy above conditions are:  26

[[ 42.  24.  38.  92.]
 [124.  39.  69.  91.]
 [126.  31.  70.  77.]
 [128.  40.  71.  95.]
 [136.  29.  73.  88.]
 [142.  32.  75.  93.]
 [144.  32.  76.  87.]
 [146.  28.  77.  97.]
 [150.  34.  78.  90.]
 [152.  39.  78.  88.]
 [154.  38.  78.  76.]
 [156.  27.  78.  89.]
 [158.  30.  78.  78.]
 [162.  29.  79.  83.]
 [164.  31.  81.  93.]
 [168.  33.  86.  95.]
 [174.  36.  87.  92.]
 [176.  30.  88.  86.]
 [180.  35.  93.  90.]
 [182.  32.  97.  86.]
 [184.  29.  98.  88.]
 [186.  30.  99.  97.]
 [190.  36. 103.  85.]
 [194.  38. 113.  91.]
 [196.  35. 120.  79.]
 [200.  30. 137.  83.]]


### Task5:

In [85]:
gift=np.random.randint(10,50,200)
gift2d=gift.reshape(-1,1)
new_data=np.append(data,gift2d,axis=1)
print(new_data)

[[  1.  19.  15.  39.  40.]
 [  2.  21.  15.  81.  45.]
 [  3.  20.  16.   6.  15.]
 [  4.  23.  16.  77.  19.]
 [  5.  31.  17.  40.  16.]
 [  6.  22.  17.  76.  19.]
 [  7.  35.  18.   6.  42.]
 [  8.  23.  18.  94.  26.]
 [  9.  64.  19.   3.  39.]
 [ 10.  30.  19.  72.  10.]
 [ 11.  67.  19.  14.  24.]
 [ 12.  35.  19.  99.  46.]
 [ 13.  58.  20.  15.  12.]
 [ 14.  24.  20.  77.  39.]
 [ 15.  37.  20.  13.  21.]
 [ 16.  22.  20.  79.  37.]
 [ 17.  35.  21.  35.  17.]
 [ 18.  20.  21.  66.  48.]
 [ 19.  52.  23.  29.  46.]
 [ 20.  35.  23.  98.  44.]
 [ 21.  35.  24.  35.  19.]
 [ 22.  25.  24.  73.  48.]
 [ 23.  46.  25.   5.  44.]
 [ 24.  31.  25.  73.  12.]
 [ 25.  54.  28.  14.  28.]
 [ 26.  29.  28.  82.  43.]
 [ 27.  45.  28.  32.  20.]
 [ 28.  35.  28.  61.  16.]
 [ 29.  40.  29.  31.  48.]
 [ 30.  23.  29.  87.  12.]
 [ 31.  60.  30.   4.  46.]
 [ 32.  21.  30.  73.  41.]
 [ 33.  53.  33.   4.  20.]
 [ 34.  18.  33.  92.  29.]
 [ 35.  49.  33.  14.  13.]
 [ 36.  21.  33.  81