In [2]:
import numpy as np

### Task1:

In [7]:
adm_data=np.genfromtxt('DS1_C4_S1_AdmissionPredict_Data_Practice.csv',delimiter=',',skip_header=1)

In [8]:
print(adm_data)

[[  1.   337.   118.   ...   9.65   1.     0.92]
 [  2.   324.   107.   ...   8.87   1.     0.76]
 [  3.   316.   104.   ...   8.     1.     0.72]
 ...
 [398.   330.   116.   ...   9.45   1.     0.91]
 [399.   312.   103.   ...   8.78   0.     0.67]
 [400.   333.   117.   ...   9.66   1.     0.95]]


### Task2:

In [14]:
gre=adm_data[:,1]
print(gre)

[337. 324. 316. 322. 314. 330. 321. 308. 302. 323. 325. 327. 328. 307.
 311. 314. 317. 319. 318. 303. 312. 325. 328. 334. 336. 340. 322. 298.
 295. 310. 300. 327. 338. 340. 331. 320. 299. 300. 304. 307. 308. 316.
 313. 332. 326. 322. 329. 339. 321. 327. 313. 312. 334. 324. 322. 320.
 316. 298. 300. 311. 309. 307. 304. 315. 325. 325. 327. 316. 318. 328.
 332. 336. 321. 314. 314. 329. 327. 301. 296. 294. 312. 340. 320. 322.
 340. 319. 315. 317. 314. 316. 318. 299. 298. 301. 303. 304. 306. 331.
 332. 323. 322. 312. 314. 317. 326. 316. 329. 338. 331. 304. 305. 321.
 301. 320. 311. 310. 299. 290. 296. 327. 335. 334. 310. 308. 301. 300.
 323. 319. 326. 333. 339. 303. 309. 323. 333. 314. 312. 316. 326. 318.
 329. 332. 331. 340. 325. 320. 315. 326. 339. 311. 334. 332. 321. 324.
 326. 312. 315. 309. 306. 297. 315. 298. 318. 317. 329. 322. 302. 313.
 293. 311. 312. 334. 322. 323. 321. 320. 329. 319. 309. 307. 300. 305.
 299. 314. 316. 327. 317. 335. 331. 324. 324. 323. 322. 336. 316. 307.
 306. 

### Task3:

In [28]:
a3=np.where(gre>320)
a_3=np.array(a3)
a_3.size

163

### Task4:

In [34]:
index=np.where(adm_data[:,2]>110)

In [42]:
a4=adm_data[:,8][index]*100
print(a4)

[92. 90. 84. 78. 70. 94. 95. 97. 94. 91. 90. 94. 87. 91. 86. 89. 78. 78.
 72. 52. 55. 61. 78. 94. 96. 93. 72. 74. 96. 92. 94. 86. 90. 79. 74. 87.
 91. 93. 94. 94. 85. 78. 84. 92. 96. 79. 89. 80. 90. 92. 97. 80. 81. 83.
 96. 93. 94. 86. 81. 89. 89. 87. 85. 90. 89. 93. 93. 88. 90. 86. 94. 97.
 97. 95. 96. 94. 93. 91. 76. 71. 82. 91. 88. 85. 86. 70. 76. 77. 93. 85.
 90. 70. 83. 89. 80. 94. 93. 92. 89. 86. 90. 71. 80. 79. 80. 81. 80. 80.
 83. 94. 93. 91. 86. 95. 96. 96. 84. 89. 91. 95.]


### Task5:

In [49]:
index5=np.where((adm_data[:,1]>315)&(adm_data[:,2]>115)&(adm_data[:,7]>0))

In [52]:
a5=adm_data[:,0][index5]
print(a5)

[  1.  23.  24.  25.  26.  33.  53.  71.  82.  98.  99. 108. 109. 121.
 122. 130. 139. 142. 144. 149. 152. 172. 177. 188. 194. 203. 204. 213.
 214. 215. 216. 260. 286. 287. 326. 338. 362. 373. 386. 398. 400.]


In [53]:
a5.size

41